export const HOTEL_NAME_HE_MAP: Record<string, string> = {
  "Leonardo Boutique Hotel Linz City Center": "מלון לאונרדו בוטיק לינץ סיטי סנטר",
  "Leonardo Boutique Hotel Salzburg Gablerbräu": "מלון לאונרדו בוטיק זלצבורג גבלרברוי",
  "Leonardo Hotel Salzburg City Center": "מלון לאונרדו זלצבורג סיטי סנטר",
  "Leonardo Hotel Salzburg Airport": "מלון לאונרדו זלצבורג נמל התעופה",
  "Leonardo Hotel Vienna Westbahnhof": "מלון לאונרדו וינה ווסטבאנהוף",
  "Leonardo Hotel Vienna City West": "מלון לאונרדו וינה סיטי ווסט",
  "Leonardo Hotel Vienna Hauptbahnhof": "מלון לאונרדו וינה האופטבנהוף",
  "Leonardo Hotel Vienna Schönbrunn": "מלון לאונרדו וינה שונברון",
  "Leonardo Hotel Antwerpen": "מלון לאונרדו אנטוורפן",
  "Leonardo Hotel Antwerp the Plaza": "מלון לאונרדו אנטוורפן פלאזה",
  "Leonardo Boutique Hotel Larnaca": "מלון לאונרדו בוטיק לרנקה",
  "The GrandResort - Leonardo Limited Edition": "מלון לאונרדו גראנד ריזורט - לאונרדו לימיטד אדישן",
  "NYX Hotel Limassol": "מלון NYX לימסול",
  "Leonardo Plaza Cypria Maris Beach Hotel & Spa": "מלון לאונרדו פלאזה סיפריה מאריס ביץ' וספא",
  "Leonardo Laura Beach & Splash Resort": "מלון לאונרדו לאורה ביץ' ספלאש",
  "Leonardo Cypria Bay": "מלון סיפריה ביי פאפוס",
  "Leonardo Crystal Cove Hotel & Spa by the Sea - Adults Only": "מלון לאונרדו קריסטל קוב ליד הים - למבוגרים בלבד",
  "NYX Hotel Prague": "מלון NYX פראג",
  "Leonardo Boutique Hotel Paris Opera": "מלון לאונרדו בוטיק פריז אופרה",
  "Leonardo Hotel Aachen": "מלון לאונרדו אאכן",
  "Leonardo Hotel Augsburg": "מלון לאונרדו אוגסבורג",
  "Leonardo Hotel Bad Kreuznach": "מלון לאונרדו באד קרויצנאך",
  "Leonardo Royal Hotel Baden-Baden": "מלון לאונרדו רויאל באדן באדן",
  "Badischer Hof - Leonardo Limited Edition": "באדישר הוף – מהדורה מוגבלת של לאונרדו",
  "Leonardo Royal Hotel Berlin Alexanderplatz": "מלון לאונרדו רויאל ברלין אלכסנדרפלאץ",
  "The Posthouse Berlin Potsdamer Platz – Leonardo Limited Edition": "פוסטהאוס ברלין פוטסדאמר פלאץ – לאונרדו לימיטד אדישן",
  "Leonardo Hotel Berlin Mitte": "מלון לאונרדו ברלין מיטה",
  "Leonardo Hotel Berlin": "מלון לאונרדו ברלין",
  "Leonardo Boutique Hotel Berlin City South": "מלון לאונרדו בוטיק ברלין",
  "Leonardo Hotel Berlin KU´DAMM": "מלון לאונרדו ברלין קודאם",
  "NYX Hotel Berlin Köpenick": "מלון NYX ברלין קפניק",
  "Leonardo Royal Hotel Cologne Bonn Airport": "מלון לאונרדו רויאל שדה התעופה קלן",
  "Leonardo Royal Hotel Köln Am Stadtwald": "מלון לאונרדו רויאל קלן",
  "Leonardo Hotel Köln": "מלון לאונרדו קלן",
  "Leonardo Hotel Köln Bonn Airport": "מלון לאונרדו שדה התעופה קלן",
  "Leonardo Hotel Dortmund": "מלון לאונרדו דורטמונד",
  "Leonardo Hotel Dresden Altstadt": "מלון לאונרדו דרזדן אלטשטאדט",
  "Leonardo Royal Hotel Düsseldorf Königsallee": "מלון לאונרדו רויאל דיסלדורף",
  "Leonardo Boutique Hotel Düsseldorf": "מלון לאונרדו בוטיק דיסלדורף",
  "Leonardo Hotel Düsseldorf City Center": "מלון לאונרדו דיסלדורף סיטי סנטר",
  "Leonardo Hotel Düsseldorf Airport - Ratingen": "מלון לאונרדו שדה התעופה דיסלדורף",
  "NYX Hotel Erfurt": "מלון NYX ארפורט",
  "Hotel Erfurt City Center by Leonardo Hotels": "מלון Erfurt City Center by Leonardo Hotels",
  "Leonardo Hotel Esslingen": "מלון לאונרדו אסלינגן",
  "Leonardo Royal Hotel Frankfurt": "מלון לאונרדו רויאל פרנקפורט",
  "Leonardo Hotel Frankfurt City South": "מלון לאונרדו פרנקפורט סיטי סאות'",
  "Leonardo Hotel Frankfurt City Center": "מלון לאונרדו פרנקפורט סיטי סנטר",
  "Leonardo Hotel Eschborn Frankfurt": "מלון לאונרדו אשבורן פרנקפורט",
  "Leonardo Hotel Offenbach Frankfurt": "מלון לאונרדו אופנבך פרנקפורט",
  "Hotel Freiburg City Center by Leonardo Hotels": "מלון פרייבורג סיטי סנטר מאת לאונרדו הוטלס",
  "The Nikolai Hotel Hamburg - Leonardo Limited Edition": "מלון ניקולאי המבורג - לאונרדו לימיטד אדישן",
  "NYX Hotel Hamburg": "מלון NYX המבורג",
  "Leonardo Hotel Hamburg Altona": "מלון לאונרדו המבורג אלטונה",
  "Leonardo Hotel Hamburg City Nord": "מלון לאונרדו המבורג סיטי נורד",
  "Leonardo Hotel Hamburg Elbbrücken": "מלון לאונרדו המבורג אלברוקן",
  "Leonardo Hotel Hamburg-Stillhorn": "מלון לאונרדו המבורג-שטילהורן",
  "Leonardo Hotel Hamburg Airport": "מלון לאונרדו המבורג איירפורט",
  "Leonardo Inn Hotel Hamburg Airport": "מלון לאונרדו אין שדה התעופה המבורג",
  "Leonardo Hotel Hannover": "מלון לאונרדו האנובר",
  "Leonardo Hotel Hannover Airport": "מלון לאונרדו שדה התעופה האנובר",
  "Leonardo Hotel Hannover Medical Park": "מלון לאונרדו האנובר מדיקל פארק",
  "Leonardo Hotel Heidelberg City Center": "מלון לאונרדו היידלברג סיטי סנטר",
  "Leonardo Hotel Heidelberg": "מלון לאונרדו היידלברג",
  "Leonardo Hotel Heidelberg-Walldorf": "מלון לאונרדו היידלברג וולדורף",
  "Leonardo Hotel Karlsruhe": "מלון לאונרדו קרלסרוהה",
  "Hotel Magdeburg City Center by Leonardo Hotels": "מלון מגדבורג סיטי סנטר מבית לאונרדו הוטלס",
  "Leonardo Hotel Mainz": "מלון לאונרדו מיינץ",
  "Hotel Mannheimer Hof - Leonardo Limited Edition": "מלון מנהיימר הוף - מהדורת לאונרדו המוגבלת",
  "NYX Hotel Mannheim": "מלון NYX מנהיים",
  "Leonardo Hotel Mannheim City Center": "מלון לאונרדו סיטי סנטר מנהיים",
  "Leonardo Hotel Mannheim-Ladenburg": "מלון לאונרדו מנהיים לדנבורג",
  "Leonardo Hotel Mönchengladbach": "מלון לאונרדו מנשנגלדבאך",
  "Leonardo Royal Hotel Munich": "מלון לאונרדו רויאל מינכן",
  "NYX Hotel Munich": "מלון ניקס מינכן",
  "Leonardo Boutique Hotel Munich": "מלון לאונרדו בוטיק מינכן",
  "Leonardo Hotel Munich City Olympiapark": "מלון לאונרדו מינכן סיטי אולימפיה פארק",
  "Leonardo Hotel Munich Arabellapark": "מלון לאונרדו מינכן ארבלה פארק",
  "Leonardo Hotel München City Center": "מלון לאונרדו מינכן סיטי סנטר",
  "Leonardo Hotel Munich City East": "מלון לאונרדו מינכן סיטי איסט",
  "Leonardo Hotel Munich City South": "מלון לאונרדו מינכן סיטי סאות'",
  "Leonardo Hotel Munich City North": "מלון לאונרדו מינכן סיטי נורת'",
  "Leonardo Hotel München City West": "מלון לאונרדו מינכן סיטי ווסט",
  "Leonardo Hotel & Residenz München": "מלון לאונרדו רזידנס מינכן",
  "Leonardo Royal Hotel Nürnberg": "מלון לאונרדו רויאל נירנברג",
  "Leonardo Hotel Nürnberg": "מלון לאונרדו נירנברג",
  "Hotel Nürnberg City Center by Leonardo Hotels": "מלון נירנברג סיטי סנטר מאת לאונרדו הוטלס",
  "Leonardo Royal Hotel Ulm": "מלון לאונרדו רויאל אולם",
  "Leonardo Hotel Völklingen-Saarbrücken": "מלון לאונרדו וולקלינגן סארברוקן",
  "Leonardo Hotel Weimar": "מלון לאונרדו ויימאר",
  "Leonardo Hotel Wolfsburg City Center": "מלון לאונרדו וולפסבורג סיטי סנטר",
  "NYX Hotel Esperia Palace Athens": "מלון ניקס אספריה פאלאס אתונה",
  "SEAFOS Luxury Resort and Spa - Nafplio Limited Edition by Leonardo Hotels": "מלון SEAFOS Luxury Resort and Spa נאפפליו - לאונרדו לימיטד אדישן",
  "Leonardo Kolymbia Resort Rhodes": "מלון לאונרדו קולימביה ריזורט רודוס",
  "NYX Hotel Thessaloniki": "מלון NYX סלוניקי",
  "Leonardo Boutique Hotel Budapest M-Square": "מלון לאונרדו בוטיק בודפשט",
  "Leonardo Hotel Budapest": "מלון לאונרדו בודפשט",
  "Leonardo Plaza Hotel Ashdod": "מלון לאונרדו פלאזה אשדוד",
  "Leonardo Hotel Negev": "מלון לאונרדו נגב באר שבע",
  "Leonardo Plaza Dead Sea": "מלון לאונרדו פלאזה ים המלח",
  "Herods Dead Sea Hotel": "מלון הרודס ים המלח",
  "Leonardo Club Dead Sea": "מלון לאונרדו קלאב ים המלח",
  "Leonardo Inn Dead Sea": "מלון לאונרדו אין ים המלח",
  "Herods Vitalis Eilat Hotel": "מלון הרודס ויטאליס אילת",
  "Herods Boutique Eilat Hotel": "מלון הרודס בוטיק אילת",
  "Herods Palace Eilat Hotel": "מלון הרודס פאלאס אילת",
  "Leonardo Royal Resort Eilat": "מלון לאונרדו רויאל ריזורט אילת",
  "Leonardo Plaza Hotel Eilat": "מלון לאונרדו פלאזה אילת",
  "Leonardo Club Hotel Eilat - All Inclusive": "מלון לאונרדו קלאב הכל כלול אילת",
  "Leonardo Privilege Hotel Eilat - All Inclusive": "מלון לאונרדו פריוילג' הכל כלול אילת",
  "U Coral Beach Club Eilat Ultra All Inclusive": "מלון יו קורל ביץ' קלאב אילת אולטרה הכל כלול",
  "U Magic Palace Eilat": "מלון יו מג'יק פאלאס אילת",
  "U Splash Resort": "מלון יו ספלאש ריזורט אילת",
  "Hotel Botanica Haifa": "מלון בוטניקה חיפה",
  "Leonardo Plaza Haifa": "מלון לאונרדו פלאזה חיפה",
  "Herods Herzliya": "הרודס הרצליה",
  "NYX Hotel Herzliya": "מלון NYX הרצליה",
  "THE YACHT": "THE YACHT",
  "Leonardo Boutique Jerusalem": "מלון לאונרדו בוטיק ירושלים",
  "Leonardo Hotel Jerusalem": "מלון לאונרדו ירושלים",
  "Leonardo Plaza Hotel Jerusalem": "מלון לאונרדו פלאזה ירושלים",
  "Nucha Hotel": "מלון נוצ'ה",
  "Leonardo Plaza Netanya": "מלון לאונרדו פלאזה נתניה",
  "Leonardo Plaza City Tower Hotel": "מלון לאונרדו פלאזה סיטי טאוור",
  "Leonardo Boutique Rehovot": "מלון לאונרדו בוטיק רחובות",
  "Canaan Hotel": "מלון כנען",
  "Herods Tel Aviv Hotel": "מלון הרודס תל אביב",
  "NYX Hotel Tel Aviv": "מלון NYX תל אביב",
  "Leonardo Boutique Hotel Tel Aviv": "מלון לאונרדו בוטיק תל אביב",
  "Hotel Rothschild 22 Tel Aviv": "מלון רוטשילד 22 תל אביב",
  "Leonardo Gordon Beach Tel Aviv": "מלון לאונרדו גורדון ביץ' תל אביב",
  "Bachar House": "מלון בכר האוס",
  "Nordoy Hotel": "נורדוי",
  "Sam & Blondi": "מלון סאם ובלונדי",
  "Bazaar Hotel": "מלון בזאר-Bazaar",
  "The Jaffa": "The Jaffa",
  "Hotel RECEPTION": "מלון ריספשן",
  "U Boutique Kinneret": "מלון יו בוטיק כנרת",
  "Leonardo Tiberias": "מלון לאונרדו טבריה",
  "Leonardo Plaza Tiberias": "מלון לאונרדו פלאזה טבריה",
  "Leonardo Club Tiberias": "מלון לאונרדו קלאב טבריה - הכל כלול",
  "Leonardo Hotel Lago di Garda – Wellness and Spa": "מלון לאונרדו לאגו די גארדה – בריאות וספא",
  "NYX Hotel Milan": "מלון NYX מילאנו",
  "Leonardo Hotel Milan City Center": "מלון לאונרדו מילאנו סיטי סנטר",
  "Leonardo Boutique Hotel Rome Termini": "מלון לאונרדו בוטיק רומא טרמיני",
  "NYX Hotel Rome": "מלון ניקס רומא",
  "Leonardo Boutique Hotel Rome Monti": "מלון לאונרדו בוטיק רומא מונטי",
  "Leonardo Royal Hotel Venice Mestre": "מלון לאונרדו רויאל ונציה מסטרה",
  "Leonardo Hotel Verona": "מלון לאונרדו ורונה",
  "Leonardo Hotel Almere City Center": "מלון לאונרדו אלמרה סיטי סנטר",
  "Leonardo Royal Hotel Amsterdam": "מלון לאונרדו רויאל אמסטרדם",
  "Leonardo Eden Hotel Amsterdam City Center": "מלון לאונרדו עדן אמסטרדם סיטי סנטר",
  "NYX Hotel Amsterdam Rembrandt Square": "מלון NYX אמסטרדם כיכר רמברנדט",
  "Jan Luyken Amsterdam by Leonardo Hotels": "יאן לויקן אמסטרדם",
  "The Manor Amsterdam": "The Manor אמסטרדם",
  "Leonardo Boutique Hotel The Lancaster Amsterdam": "מלון לאונרדו בוטיק דה לנקסטר אמסטרדם",
  "Leonardo Hotel Amsterdam Museum Quarter": "מלון לאונרדו אמסטרדם מוזיאון קוורטר",
  "Leonardo Boutique Hotel Amsterdam Vondelpark": "Leonardo Boutique Hotel Amsterdam Vondelpark",
  "Leonardo Hotel Amsterdam Rembrandtpark": "מלון לאונרדו אמסטרדם רמברנדט פארק",
  "Leonardo Hotel Amsterdam Leidse Square": "מלון לאונרדו אמסטרדם כיכר ליידסה",
  "Leonardo Hotel Vinkeveen Amsterdam": "מלון לאונרדו אמסטרדם וינקביין",
  "Leonardo Hotel Breda City Center": "מלון לאונרדו ברדה סיטי סנטר",
  "Leonardo Hotel Eindhoven City Center": "מלון לאונרדו מרכז העיר איינדהובן",
  "Leonardo Hotel Groningen Stadspark": "מלון לאונרדו גרונינגן סטדספארק",
  "Leonardo Hotel Groningen City Center": "מלון לאונרדו מרכז העיר חרונינגן",
  "Leonardo Hotel Hengelo City Center": "מלון לאונרדו הנגלו סיטי סנטר",
  "Leonardo Hotel IJmuiden Seaport Beach": "מלון לאונרדו איימאודן",
  "Leonardo Oranje Hotel Leeuwarden": "מלון לאונרדו אורנייה לייווארדן",
  "Leonardo Hotel Lelystad City Center": "מלון לאונרדו לייליסטאד סיטי סנטר",
  "Leonardo Boutique Hotel Maastricht City Center": "מלון לאונרדו בוטיק מאסטריכט סיטי סנטר",
  "Leonardo Hotel Papendrecht": "מלון לאונרדו פפנדרכט",
  "Leonardo Hotel Rotterdam Savoy": "מלון ליאונרדו רוטרדם סבוי",
  "Leonardo Royal Hotel Den Haag Promenade": "מלון לאונרדו רויאל האג פרומנייד",
  "Leonardo Hotel Den Haag Babylon": "מלון לאונרדו האג בבילון",
  "Leonardo Hotel Utrecht City Center": "מלון לאונרדו אוטרכט סיטי סנטר",
  "Leonardo Boutique Hotel Krakow Old Town": "מלון לאונרדו בוטיק קרקוב העיר העתיקה",
  "Leonardo Boutique Hotel Krakow City Center": "מלון לאונרדו בוטיק קרקוב סיטי סנטר",
  "Leonardo Royal Hotel Warsaw": "מלון לאונרדו רויאל ורשה",
  "NYX Hotel Warsaw": "מלון NYX ורשה",
  "Leonardo Hotel Cork": "מלון ג'וריס אין קורק",
  "Leonardo Hotel Dublin Parnell Street": "מלון ג'וריס אין דבלין פארנל סטריט",
  "Leonardo Hotel Dublin Christchurch": "מלון לאונרדו דבלין מלון כריסט צ'רץ'",
  "NYX Hotel Dublin Portobello": "מלון NYX דבלין פורטובלו",
  "NYX Hotel Dublin Christchurch": "מלון NYX דבלין כרייסטצ'רץ'",
  "Leonardo Hotel Galway": "מלון לאונרדו גלוואי",
  "The g Hotel": "מלון g",
  "Leonardo Hotel Bucharest City Center": "מלון לאונרדו בוקרשט סיטי סנטר",
  "Leonardo Boutique Hotel Barcelona Sagrada Familia": "מלון לאונרדו בוטיק ברצלונה סגרדה פמיליה",
  "Leonardo Hotel Barcelona Las Ramblas": "מלון לאונרדו ברצלונה לאס רמבלס",
  "Leonardo Hotel Barcelona Gran Via": "מלון לאונרדו ברצלונה גראן ויה",
  "Leonardo Royal Hotel Barcelona Fira": "מלון לאונרדו רויאל ברצלונה פירה",
  "Leonardo Royal Hotel Barcelona Forum": "לאונרדו רויאל הוטל ברצלונה פורום",
  "NYX Hotel Bilbao": "מלון ניקס בילבאו",
  "Leonardo Hotel Fuengirola Costa Del Sol": "מלון לאונרדו קוסטה דל סול פואנג'ירולה",
  "Leonardo Hotel Torremolinos Costa del Sol": "מלון לאונרדו טורמולינוס קוסטה דל סול",
  "Leonardo Hotel San Sebastián": "מלון לאונרדו סן סבסטיאן",
  "Leonardo Boutique Hotel San Sebastián": "מלון לאונרדו בוטיק סן סבסטיאן",
  "Leonardo Royal Hotel Ibiza Santa Eulalia": "מלון לאונרדו רויאל איביזה סנטה אולליה",
  "NYX Hotel Ibiza - Adults Only": "מלון NYX איביזה - למבוגרים בלבד",
  "Leonardo Suites Hotel Ibiza Santa Eulalia": "מלון לאונרדו איביזה סנטה אולליה סוויטות",
  "NYX Hotel Madrid": "מלון NYX מדריד",
  "Leonardo Boutique Hotel Madrid": "מלון לאונרדו בוטיק מדריד",
  "Leonardo Hotel Madrid City Center": "מלון לאונרדו מדריד סיטי סנטר",
  "Leonardo Boutique Hotel Mallorca Port Portals - Adults Only": "מלון לאונרדו בוטיק מיורקה פורט - למבוגרים בלבד",
  "Leonardo Royal Hotel Mallorca": "מלון לאונרדו רויאל מיורקה",
  "Leonardo Suites Hotel Mallorca Calvia": "מלון לאונרדו סוויט מיורקה קלביה",
  "Leonardo Royal Hotel Mallorca Palmanova Bay": "מלון לאונרדו רויאל מיורקה פלמנובה ביי",
  "Hotel Alden Splügenschloss Zürich - Leonardo Limited Edition": "מלון Alden Splügenschloss ציריך - מהדורה מוגבלת של לאונרדו",
  "Leonardo Boutique Hotel Rigihof Zurich": "מלון לאונרדו בוטיק ציריך",
  "Leonardo Hotel Zurich Airport": "מלון לאונרדו נמל התעופה ציריך",
  "Leonardo Hotel Aberdeen": "מלון לאונרדו אברדין",
  "Leonardo Hotel and Conference Venue Aberdeen Airport": "מלון לאונרדו ומרכז כנסים שדה התעופה אברדין",
  "Leonardo Inn Hotel Aberdeen Airport": "מלון לאונרדו אברדין",
  "Leonardo Hotel Belfast": "מלון לאונרדו בלפסט",
  "Leonardo Royal Hotel Birmingham": "מלון לאונרדו רויאל ברמינגהם",
  "Leonardo Hotel Bradford": "מלון לאונרדו ברדפורד",
  "Leonardo Royal Hotel Brighton Waterfront": "מלון לאונרדו רויאל ברייטון ווטרפרונט",
  "Leonardo Hotel Brighton": "מלון לאונרדו ברייטון",
  "The Grand Brighton": "הגרנד ברייטון",
  "Leonardo Hotel Bristol City": "מלון לאונרדו בריסטול סיטי",
  "Leonardo Hotel Cardiff": "מלון לאונרדו קארדיף",
  "Leonardo Hotel Cheltenham": "מלון לאונרדו צ'לטנהאם",
  "Leonardo Hotel Chester": "מלון לאונרדו צ'סטר",
  "Leonardo Hotel Derby": "מלון לאונרדו דרבי",
  "Leonardo Hotel East Midlands Airport": "מלון לאונרדו נמל התעופה מזרח מידלנדס",
  "Leonardo Hotel Edinburgh Murrayfield": "מלון לאונרדו אדינבורו מורייפילד",
  "Leonardo Hotel Edinburgh Haymarket": "מלון לאונרדו רויאל אדינבורו היימרקט",
  "Leonardo Hotel Edinburgh City": "מלון לאונרדו בוטיק אדינבורו סיטי",
  "Leonardo Royal Hotel Edinburgh": "מלון לאונרדו רויאל אדינבורו",
  "NYX Hotel Edinburgh": "מלון אדינבורו NYX",
  "Leonardo Hotel Exeter": "מלון לאונרדו אקסטר",
  "Leonardo Inn Hotel Glasgow West End": "מלון לאונרדו אין גלזגו ווסט אנד",
  "Leonardo Royal Hotel Glasgow": "מלון לאונרדו גלזגו",
  "Leonardo Hotel and Conference Venue Hinckley Island": "מלון לאונרדו ומרכז כנסים הינקלי",
  "Leonardo Hotel Inverness": "מלון לאונרדו אינברנס",
  "Leonardo Hotel Leeds": "מלון לאונרדו לידס",
  "Leonardo Hotel Liverpool": "מלון לאונרדו ליברפול",
  "Leonardo Royal Hotel London St Paul’s": "מלון לאונרדו רויאל לונדון סיינט פול",
  "NYX Hotel London Holborn": "מלון NYX לונדון הולבורן",
  "Leonardo Royal Hotel London City": "מלון לאונרדו רויאל לונדון סיטי",
  "The Dilly": "הדילי",
  "Leonardo Royal Hotel London Tower Bridge": "מלון לאונרדו רויאל לונדון טאוור ברידג'",
  "Leonardo Hotel London Heathrow Airport": "מלון לאונרדו לונדון הית'רו איירפורט",
  "Leonardo Hotel London Croydon": "מלון לאונרדו לונדון קרוידון",
  "Leonardo Hotel London Watford": "מלון לאונרדו לונדון ווטפורד",
  "The Midland": "מלון מידלנד מנצ'סטר",
  "Leonardo Hotel Manchester Central": "מלון לאונרדו מנצ'סטר מרכז",
  "Leonardo Hotel Manchester Piccadilly": "מלון לאונרדו מנצ'סטר פיקדילי",
  "Hotel Gotham": "מלון גותהאם",
  "Leonardo Hotel Middlesbrough": "מלון לאונרדו מידלסברו",
  "Leonardo Hotel Milton Keynes": "מלון לאונרדו מילטון קינס",
  "Leonardo Hotel Newcastle": "מלון לאונרדו ניוקאסל",
  "Leonardo Hotel Newcastle Quayside": "מלון לאונרדו ניוקאסל קוויסייד",
  "Leonardo Hotel Nottingham": "מלון לאונרדו נוטינגהאם",
  "Leonardo Royal Hotel Oxford": "מלון לאונרדו רויאל אוקספורד",
  "Leonardo Boutique Hotel Huntingtower Perth": "מלון לאונרדו בוטיק האנטינגטאוור פרת'",
  "Leonardo Hotel Plymouth": "מלון לאונרדו פלימות'",
  "Leonardo Hotel Sheffield": "מלון לאונרדו שפילד",
  "Leonardo Hotel Southampton": "מלון לאונרדו סאות'המפטון",
  "Leonardo Royal Hotel Southampton Grand Harbour": "מלון לאונרדו רויאל סאות'המפטון גראנד הארבור",
  "Leonardo Hotel Swindon": "מלון לאונרדו סווינדון",
};